"use client";

import { useQuery } from "@tanstack/react-query";
import Link from "next/link";

import { AparixBadge, DemoDataBadge } from "@/components/aparix/AparixBadge";
import { AparixCard } from "@/components/aparix/AparixCard";
import { AparixMetric } from "@/components/aparix/AparixMetric";
import { AparixRiskIndicator } from "@/components/aparix/AparixRiskIndicator";
import { api } from "@/lib/api";
import { useCurrentUser } from "@/lib/use-auth";
import { usePrimaryPortfolio } from "@/lib/use-portfolio";

const SEVERITY_TONE = { low: "neutral", medium: "warning", high: "negative" } as const;

function formatInr(value: number): string {
  return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(
    value
  );
}

function formatPct(value: number): string {
  return `${value >= 0 ? "+" : ""}${value.toFixed(2)}%`;
}

export default function HomePage() {
  const { data: user } = useCurrentUser();
  const { portfolio, isLoading, analytics, risk } = usePrimaryPortfolio();
  const complexityLevel = user?.preferences.complexity_level ?? 1;

  const briefing = useQuery({
    queryKey: ["ai-briefing", portfolio?.id],
    queryFn: () => api.ai.chat({ portfolio_id: portfolio!.id, message: "Give me a quick summary of my portfolio." }),
    enabled: Boolean(portfolio),
    // A briefing generated before the user added/edited a holding would go
    // stale silently otherwise — regenerate every time Home is visited
    // rather than caching across navigations.
    staleTime: 0,
    refetchOnMount: "always",
  });

  const events = useQuery({ queryKey: ["events"], queryFn: api.events.list });
  const macro = useQuery({ queryKey: ["macro-indicators"], queryFn: api.macro.indicators });
  const notableEvents = (events.data ?? []).filter((e) => e.severity !== "low").slice(0, 3);

  if (isLoading) {
    return <p className="text-sm text-muted-foreground">Loading…</p>;
  }

  if (!portfolio) {
    return (
      <AparixCard title="No portfolio yet">
        <p className="text-sm text-muted-foreground">
          Something went wrong during onboarding — no portfolio was created. Visit /onboarding to try again.
        </p>
      </AparixCard>
    );
  }

  const data = analytics.data;

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h1 className="text-lg font-semibold">{portfolio.name}</h1>
        <DemoDataBadge />
      </div>

      <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
        <AparixCard>
          <AparixMetric label="Total value" value={data ? formatInr(data.total_value) : "—"} size="lg" />
        </AparixCard>
        <AparixCard>
          <AparixMetric
            label="Day P&L"
            value={data ? formatInr(data.day_pnl) : "—"}
            delta={data ? { value: formatPct(data.day_pnl_pct), positive: data.day_pnl >= 0 } : null}
          />
        </AparixCard>
        <AparixCard>
          <AparixMetric
            label="Total P&L"
            value={data ? formatInr(data.total_pnl) : "—"}
            delta={data ? { value: formatPct(data.total_pnl_pct), positive: data.total_pnl >= 0 } : null}
          />
        </AparixCard>
        <AparixCard title="Risk score">
          {data ? <AparixRiskIndicator score={data.risk_score} /> : <span className="text-sm">—</span>}
        </AparixCard>
      </div>

      <AparixCard title="AI Briefing">
        {/* isFetching (not just isLoading) gates this: a briefing regenerates
            on every Home visit (see usePrimaryPortfolio/briefing query,
            refetchOnMount: "always"), and showing the previous holding's
            stale cached text while that's in flight would be actively
            misleading, not just momentarily behind. */}
        {briefing.isFetching && <p className="text-sm text-muted-foreground">Analyzing your portfolio…</p>}
        {!briefing.isFetching && briefing.data && <p className="text-sm">{briefing.data.message}</p>}
        <p className="mt-2 text-xs text-muted-foreground">
          {briefing.data?.provider === "ollama"
            ? "Response generated locally by Ollama — see /ai for the full terminal."
            : "Response generated by a mock provider in development mode — see /ai for the full terminal."}
        </p>
      </AparixCard>

      <AparixCard title="Market Events" action={<Link href="/events" className="text-xs text-accent hover:underline">View all →</Link>}>
        {notableEvents.length === 0 ? (
          <p className="text-sm text-muted-foreground">No notable events right now.</p>
        ) : (
          <div className="space-y-2">
            {notableEvents.map((e) => (
              <div key={e.id} className="flex items-center gap-2 text-sm">
                <AparixBadge tone={SEVERITY_TONE[e.severity]}>{e.severity}</AparixBadge>
                <span className="flex-1 truncate">{e.headline}</span>
                <span className="shrink-0 text-xs text-muted-foreground">{e.primary_target}</span>
              </div>
            ))}
          </div>
        )}
      </AparixCard>

      <AparixCard title="Macro snapshot">
        {macro.data && macro.data.length > 0 ? (
          <div className="grid grid-cols-3 gap-4 sm:grid-cols-6">
            {macro.data.map((m) => (
              <AparixMetric
                key={m.code}
                label={m.name}
                value={m.unit === "%" ? `${m.value}%` : `${m.value} ${m.unit}`}
              />
            ))}
          </div>
        ) : (
          <p className="text-sm text-muted-foreground">Loading macro data…</p>
        )}
      </AparixCard>

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        <AparixCard title="Sector exposure">
          {!data || data.sector_exposure.length === 0 ? (
            <p className="text-sm text-muted-foreground">Add holdings to see sector exposure.</p>
          ) : (
            <div className="space-y-2">
              {data.sector_exposure.map((row) => (
                <div key={row.sector}>
                  <div className="flex justify-between text-xs">
                    <span>{row.sector}</span>
                    <span className="font-mono-nums text-muted-foreground">{row.weight_pct.toFixed(1)}%</span>
                  </div>
                  <div className="mt-1 h-1.5 rounded-full bg-surface-hover">
                    <div className="h-1.5 rounded-full bg-accent" style={{ width: `${row.weight_pct}%` }} />
                  </div>
                </div>
              ))}
            </div>
          )}
        </AparixCard>

        <AparixCard title="Risk detail">
          {complexityLevel === 1 && (
            <p className="text-sm text-muted-foreground">
              Concentration score: {data?.concentration_score.toFixed(0) ?? "—"}/100. Switch to Informed or above
              in onboarding preferences for volatility and beta.
            </p>
          )}
          {complexityLevel >= 2 && (
            <div className="space-y-2 text-sm">
              <div className="flex justify-between">
                <span className="text-muted-foreground">Concentration (HHI-based)</span>
                <span className="font-mono-nums">{data?.concentration_score.toFixed(1) ?? "—"}/100</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Annualized volatility</span>
                <span className="font-mono-nums">
                  {data?.annualized_volatility_pct != null ? `${data.annualized_volatility_pct.toFixed(1)}%` : "—"}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Beta vs NIFTY 50</span>
                <span className="font-mono-nums">{data?.beta_vs_nifty?.toFixed(2) ?? "—"}</span>
              </div>
            </div>
          )}
          {complexityLevel >= 3 && (
            <div className="mt-3 space-y-2 border-t border-border pt-3 text-sm">
              {risk.data && risk.data.sample_size < 20 ? (
                <p className="text-xs text-muted-foreground">
                  Not enough price history yet for VaR/CVaR/Sharpe/Sortino ({risk.data.sample_size} days,
                  need 20+).
                </p>
              ) : (
                <>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">VaR 95% (1-day)</span>
                    <span className="font-mono-nums">
                      {risk.data?.var_95_pct != null ? `${risk.data.var_95_pct.toFixed(2)}%` : "—"}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">CVaR 95%</span>
                    <span className="font-mono-nums">
                      {risk.data?.cvar_95_pct != null ? `${risk.data.cvar_95_pct.toFixed(2)}%` : "—"}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Sharpe / Sortino</span>
                    <span className="font-mono-nums">
                      {risk.data?.sharpe_ratio?.toFixed(2) ?? "—"} / {risk.data?.sortino_ratio?.toFixed(2) ?? "—"}
                    </span>
                  </div>
                </>
              )}
              <Link href="/risk" className="inline-block text-xs text-accent hover:underline">
                View full risk & simulation workspace →
              </Link>
            </div>
          )}
        </AparixCard>
      </div>
    </div>
  );
}
