"""add corporate actions table

Revision ID: 2114dad946db
Revises: da4c5fdb88b4
Create Date: 2026-09-01 19:41:21.252153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2114dad946db'
down_revision = 'da4c5fdb88b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_actions',
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('new_security_id', sa.Uuid(), nullable=True),
    sa.Column('announcement_date', sa.Date(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['new_security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_actions_security_id'), 'corporate_actions', ['security_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corporate_actions_security_id'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    # ### end Alembic commands ###
