"""add macro indicator releases table

Revision ID: 246df63d4abe
Revises: e3a8143a7c86
Create Date: 2026-09-01 20:17:23.159328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246df63d4abe'
down_revision = 'e3a8143a7c86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_indicator_releases',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_indicator_releases_code'), 'macro_indicator_releases', ['code'], unique=False)
    op.create_index('ix_macro_releases_code_period_revision', 'macro_indicator_releases', ['code', 'period', 'revision_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_macro_releases_code_period_revision', table_name='macro_indicator_releases')
    op.drop_index(op.f('ix_macro_indicator_releases_code'), table_name='macro_indicator_releases')
    op.drop_table('macro_indicator_releases')
    # ### end Alembic commands ###
