"""add document embeddings table

Revision ID: 29dccc186adf
Revises: 246df63d4abe
Create Date: 2026-09-01 20:34:38.312073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29dccc186adf'
down_revision = '246df63d4abe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_embeddings',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('dims', sa.Integer(), nullable=False),
    sa.Column('vector', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_embeddings_article_model', 'document_embeddings', ['article_id', 'model'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_embeddings_article_model', table_name='document_embeddings')
    op.drop_table('document_embeddings')
    # ### end Alembic commands ###
