"""add financial knowledge graph tables

Revision ID: a556075a526d
Revises: cb14a22a0fe1
Create Date: 2026-09-02 01:21:49.831787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a556075a526d'
down_revision = 'cb14a22a0fe1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kg_commodities',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('kg_locations',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('kg_security_commodities',
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('commodity_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['kg_commodities.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kg_sec_comm_unique', 'kg_security_commodities', ['security_id', 'commodity_id'], unique=True)
    op.create_table('kg_security_locations',
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['kg_locations.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kg_sec_loc_unique', 'kg_security_locations', ['security_id', 'location_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kg_sec_loc_unique', table_name='kg_security_locations')
    op.drop_table('kg_security_locations')
    op.drop_index('ix_kg_sec_comm_unique', table_name='kg_security_commodities')
    op.drop_table('kg_security_commodities')
    op.drop_table('kg_locations')
    op.drop_table('kg_commodities')
    # ### end Alembic commands ###
