"""add survivorship bias fields to securities

Revision ID: cb14a22a0fe1
Revises: 29dccc186adf
Create Date: 2026-09-02 00:32:07.771977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb14a22a0fe1'
down_revision = '29dccc186adf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand (not autogenerate's default) — every
    # existing row in a non-empty `securities` table needs a real value for
    # this new NOT NULL column, and every security seeded before this
    # migration existed was, in fact, tradable.
    op.add_column('securities', sa.Column('is_tradable', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('securities', sa.Column('listed_date', sa.Date(), nullable=True))
    op.add_column('securities', sa.Column('delisted_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('securities', 'delisted_date')
    op.drop_column('securities', 'listed_date')
    op.drop_column('securities', 'is_tradable')
    # ### end Alembic commands ###
