"""add financial statements table

Revision ID: da4c5fdb88b4
Revises: f8025ac717b0
Create Date: 2026-09-01 19:01:39.289557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4c5fdb88b4'
down_revision = 'f8025ac717b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_statements',
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('announcement_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('is_restated', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('shares_outstanding', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ebitda', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ebit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pbt', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pat', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('eps', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_assets', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_liabilities', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash_and_equivalents', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_debt', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('current_assets', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('current_liabilities', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_expense', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cfo', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cfi', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cff', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('free_cash_flow', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_statements_security_id'), 'financial_statements', ['security_id'], unique=False)
    op.create_index('ix_financial_statements_security_period', 'financial_statements', ['security_id', 'period_end', 'period_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_financial_statements_security_period', table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_security_id'), table_name='financial_statements')
    op.drop_table('financial_statements')
    # ### end Alembic commands ###
